import type { Metadata } from 'next'
import { Inter, Raleway, Poppins, Work_Sans } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'], variable: '--font-raleway' })
const poppins = Poppins({
  weight: ['400', '500', '600', '700', '900'],
  subsets: ['latin'],
  variable: '--font-poppins'
})
const workSans = Work_Sans({
  subsets: ['latin'],
  variable: '--font-work-sans'
})

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${raleway.variable} ${poppins.variable} ${workSans.variable}`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  )
}
